SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS seo1 FOR gs_ogr-ogr_id VISIBLE LENGTH 10.
SELECT-OPTIONS seo2 FOR gs_ogr-ogr_ad VISIBLE LENGTH 10.
SELECT-OPTIONS seo3 FOR gs_ogr-ogr_syd VISIBLE LENGTH 10.
SELECTION-SCREEN SKIP 2.
SELECTION-SCREEN PUSHBUTTON /1(25) button1 USER-COMMAND but1.
SELECTION-SCREEN END OF BLOCK bl1.

SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF BLOCK bl2.
PARAMETERS: p_vari TYPE disvariant-variant.
SELECTION-SCREEN END OF BLOCK bl2.