*& Include          ZABAP_FA_TUTORIAL_008_SS
*&---------------------------------------------------------------------*
START-OF-SELECTION.

SELECTION-SCREEN BEGIN OF BLOCK bl1 .

SELECTION-SCREEN COMMENT 1(20) v_text .

PARAMETERS: p_rad1 TYPE bkpf-bukrs MODIF ID p1,
            p_rad2 TYPE bkpf-gjahr MODIF ID p2,
            p_rad3 TYPE bkpf-monat MODIF ID p3.

SELECTION-SCREEN END OF BLOCK bl1.


SELECTION-SCREEN SKIP 3.

SELECTION-SCREEN COMMENT 1(30) v_text2.
SELECTION-SCREEN BEGIN OF BLOCK bl2.
PARAMETERS: p_list TYPE char1 AS LISTBOX VISIBLE LENGTH 10 DEFAULT 'D' USER-COMMAND list OBLIGATORY.

SELECTION-SCREEN END OF BLOCK bl2.

SELECTION-SCREEN SKIP 2.

SELECTION-SCREEN COMMENT 1(30) v_text3.

SELECTION-SCREEN BEGIN OF BLOCK bl3.

SELECT-OPTIONS seo_cus FOR wa_bseg-kunnr.
SELECT-OPTIONS seo_sel FOR wa_bseg-lifnr.

SELECTION-SCREEN END OF BLOCK bl3.


SELECTION-SCREEN SKIP 3.
SELECTION-SCREEN BEGIN OF BLOCK bl4.
SELECTION-SCREEN COMMENT /1(30) v_text4.
SELECTION-SCREEN PUSHBUTTON  /2(30) but1 USER-COMMAND but1.
SELECTION-SCREEN PUSHBUTTON  35(30) but2 USER-COMMAND but2.
SELECTION-SCREEN PUSHBUTTON  /2(30) but3 USER-COMMAND but3.
SELECTION-SCREEN PUSHBUTTON  35(30) but4 USER-COMMAND but4.
SELECTION-SCREEN END OF BLOCK bl4.